version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=webapp.py
      - FLASK_ENV=development
    volumes:
      - .:/app
    command: python webapp.py